module "kms" {
  for_each = var.kms_parameters
  source   = "terraform-aws-modules/kms/aws"
  version  = "4.0.0"

  aliases                                = try(each.value.aliases, var.kms_defaults.aliases, [each.key])
  aliases_use_name_prefix                = try(each.value.aliases_use_name_prefix, var.kms_defaults.aliases_use_name_prefix, false)
  bypass_policy_lockout_safety_check     = try(each.value.bypass_policy_lockout_safety_check, var.kms_defaults.bypass_policy_lockout_safety_check, null)
  computed_aliases                       = try(each.value.computed_aliases, var.kms_defaults.computed_aliases, {})
  create                                 = try(each.value.create, var.kms_defaults.create, true)
  create_external                        = try(each.value.create_external, var.kms_defaults.create_external, false)
  create_replica                         = try(each.value.create_replica, var.kms_defaults.create_replica, false)
  create_replica_external                = try(each.value.create_replica_external, var.kms_defaults.create_replica_external, false)
  custom_key_store_id                    = try(each.value.custom_key_store_id, var.kms_defaults.custom_key_store_id, null)
  customer_master_key_spec               = try(each.value.customer_master_key_spec, var.kms_defaults.customer_master_key_spec, null)
  deletion_window_in_days                = try(each.value.deletion_window_in_days, var.kms_defaults.deletion_window_in_days, null)
  description                            = try(each.value.description, var.kms_defaults.description, null)
  enable_default_policy                  = try(each.value.enable_default_policy, var.kms_defaults.enable_default_policy, true)
  enable_key_rotation                    = try(each.value.enable_key_rotation, var.kms_defaults.enable_key_rotation, true)
  enable_route53_dnssec                  = try(each.value.enable_route53_dnssec, var.kms_defaults.enable_route53_dnssec, false)
  grants                                 = try(each.value.grants, var.kms_defaults.grants, null)
  is_enabled                             = try(each.value.is_enabled, var.kms_defaults.is_enabled, null)
  key_administrators                     = try(each.value.key_administrators, var.kms_defaults.key_administrators, [])
  key_asymmetric_public_encryption_users = try(each.value.key_asymmetric_public_encryption_users, var.kms_defaults.key_asymmetric_public_encryption_users, [])
  key_asymmetric_sign_verify_users       = try(each.value.key_asymmetric_sign_verify_users, var.kms_defaults.key_asymmetric_sign_verify_users, [])
  key_hmac_users                         = try(each.value.key_hmac_users, var.kms_defaults.key_hmac_users, [])
  key_material_base64                    = try(each.value.key_material_base64, var.kms_defaults.key_material_base64, null)
  key_owners                             = try(each.value.key_owners, var.kms_defaults.key_owners, [])
  key_service_roles_for_autoscaling      = try(each.value.key_service_roles_for_autoscaling, var.kms_defaults.key_service_roles_for_autoscaling, [])
  key_service_users                      = try(each.value.key_service_users, var.kms_defaults.key_service_users, [])
  key_statements                         = try(each.value.key_statements, var.kms_defaults.key_statements, null)
  key_symmetric_encryption_users         = try(each.value.key_symmetric_encryption_users, var.kms_defaults.key_symmetric_encryption_users, [])
  key_usage                              = try(each.value.key_usage, var.kms_defaults.key_usage, null)
  key_users                              = try(each.value.key_users, var.kms_defaults.key_users, [])
  multi_region                           = try(each.value.multi_region, var.kms_defaults.multi_region, false)
  override_policy_documents              = try(each.value.override_policy_documents, var.kms_defaults.override_policy_documents, [])
  policy                                 = try(each.value.policy, var.kms_defaults.policy, null)
  primary_external_key_arn               = try(each.value.primary_external_key_arn, var.kms_defaults.primary_external_key_arn, null)
  primary_key_arn                        = try(each.value.primary_key_arn, var.kms_defaults.primary_key_arn, null)
  region                                 = try(each.value.region, var.kms_defaults.region, null)
  rotation_period_in_days                = try(each.value.rotation_period_in_days, var.kms_defaults.rotation_period_in_days, null)
  route53_dnssec_sources                 = try(each.value.route53_dnssec_sources, var.kms_defaults.route53_dnssec_sources, null)
  source_policy_documents                = try(each.value.source_policy_documents, var.kms_defaults.source_policy_documents, [])
  valid_to                               = try(each.value.valid_to, var.kms_defaults.valid_to, null)

  tags = merge(local.common_tags, try(each.value.tags, var.kms_defaults.tags, null))
}